# -*- coding: utf-8 -*-
"""Aula6.2_IA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13_xLEoeEgZWKGBaRW4z86-WpGu3goImr
"""

# Importar libs
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

# Base (proporcionada pela prof)
dados = {
    "Idade":[18,20,22,23,25,
             27,28,30,32,34,
             36,38,40,42,44,
             46,48,50,52,55],

    "Peso":[58,60,62,64,66,
            68,70,72,74,76,
            78,80,82,84,86,
            88,90,92,94,96],

    "Altura":[1.65,1.68,1.70,1.72,1.73,
              1.75,1.76,1.77,1.78,1.79,
              1.80,1.81,1.82,1.83,1.84,
              1.85,1.86,1.87,1.88,1.90],

    "Frequencia":[2,2,3,3,3,
                  4,4,4,5,5,
                  5,5,6,6,6,
                  6,6,6,7,7]
}

academia = pd.DataFrame(dados) # o data frame irá reestruturar o dicionário (sem alterar o conteúdo) a um formato aceito pelo algoritmo
                               # O método pd.DataFrame é essencial pois os algoritmos nao aceitam dicionários como valores de entrada

# Criar um modelo nao-supervisionado usando o KMeans
modelo = KMeans(
    n_clusters = 3, # Quantidade de clusters que o modelo deverá produzir ao relacionar (encontrar padroes entre) os membros da academia
    random_state = 42 # Qual é o sentido da vida, do universo e tudo mais? 42.
)
modelo.fit(academia) # O modelo será treinado a partir do data frame proporcionado sem nenhum grupo pré-definido

# Recuperar e adicionar ao dataframe um array contendo os grupos/labels criados pela IA
academia['Grupo'] = modelo.labels_

# Visualizado o dataframe com a coluna de grupos
academia

# Visualizando os clusters e seus respectivos valores centrais (centróides)
centros = modelo.cluster_centers_
plt.figure(figsize=(8,6))
plt.scatter(academia['Idade'],
            academia['Peso'],
            c=academia['Grupo'],
            cmap='viridis',
            s=120
)
plt.scatter(centros[:,0],
            centros[:,1],
            color='red',
            s=300,
            marker='X'
)
plt.xlabel('Idade')
plt.ylabel('Peso')
plt.title('Clusters e Centróides')
plt.grid()
plt.show()