# -*- coding: utf-8 -*-
"""Aula8.3_IA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XZ3gnQuKOM6Eya7BBLxMlHffR-UTH9At
"""

# ingredientes pro bolo de chocolate
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

# Criando a base de dados
dados = pd.DataFrame({

    "nota1":[5,6,7,8,4,3,9,10,2,7,
             6,8,5,9,4,7,8,3,10,6],

    "nota2":[6,5,8,9,3,4,10,9,2,8,
             7,8,6,10,5,8,9,4,10,7],

    "frequencia":[70,75,90,95,60,55,98,100,40,88,
                  80,92,68,96,65,85,94,58,99,82],

    "aprovado":[0,0,1,1,0,0,1,1,0,1,
                1,1,0,1,0,1,1,0,1,1]

})

dados

# Separando I/O
X = dados[['nota1','nota2','frequencia']]
y = dados['aprovado']

# Dividir Treino/Teste
X_treino, X_teste, y_treino, y_teste = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Padronizar valores. Exemplo: Nota 8 -> 0.25, Frequencia 95 -> 0.78 (tá certo?)
scaler = StandardScaler()
X_treino_ssc = scaler.fit_transform(X_treino)
X_teste_ssc = scaler.transform(X_teste)

print(f'X_treino:\n{X_treino['nota1']}\nX_treino escalado:\n{X_treino_ssc}\nX_teste:\n{X_teste}\nX_teste escalado:\n{X_teste_ssc}')

# Criando a rede neural
modelo = Sequential([
    Input(shape=(3,)),
    Dense(8, activation='relu'),
    Dense(4, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compilando
modelo.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Treinando
historico = modelo.fit(
    X_treino_ssc,
    y_treino,
    epochs=100,
    verbose=1
)

# Avaliar acurácia
loss, accuracy = modelo.evaluate(X_teste_ssc, y_teste)
print(f'Precisão: {accuracy:.2f}')

# Previsões
novo_aluno = pd.DataFrame({
    'nota1': [8],
    'nota2': [8],
    'frequencia': [90]
})
novo_aluno_ssc = scaler.transform(novo_aluno)
previsao = modelo.predict(novo_aluno_ssc)
print(previsao[0][0])

# Interpretando
if previsao[0][0] >= 0.5:
  print('Aprovado')
else:
  print('Reprovado')