# -*- coding: utf-8 -*-
"""Aula9.2_IA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11BlYqig626BAtGEnhpQ-7uvuGsj-82T7
"""

!python -m spacy download pt_core_news_sm

import nltk
import spacy
import string
import pandas as pd
# Baixando os recursos do NLTK
nltk.download('punkt')
nltk.download('stopwords')

print('Bibliotecas importadas com sucesso!...')

from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')

texto_exemplo = 'Nossa! O novo smartphone da Samsung é incrível, mas a bateria dura muito pouco.'

tokens = word_tokenize(texto_exemplo, language='portuguese')
print(f'Texto Original:\n{texto_exemplo}')
print(f'Tokens:\n{tokens}')

from nltk.corpus import stopwords

stop_word_pt = set(stopwords.words('portuguese'))
tokens_limpos = []
for token in tokens:
  token_min = token.lower()
  if token_min not in string.punctuation and token_min not in stop_word_pt:
    tokens_limpos.append(token_min)

print(f'Tokens Limpos: {tokens_limpos}')
print(string.punctuation)
print(token_min)

nlp = spacy.load('pt_core_news_sm')
doc = nlp(texto_exemplo)

print('Análise gramatical e Lematização com o SPACY:')
for token in doc:
  if not token.is_punct:
    print(f'A palavra: {token.text:15} | Lema (raiz): {token.lemma_:15} | Função: {token.pos_}')

dados = {
    'comentario': [
        # --- POSITIVOS (75) ---
        'Simplesmente fantástico! Superou todas as minhas expectativas.',
        'Entrega rápida e o produto é de altíssima qualidade. Nota dez!',
        'Melhor compra que fiz este ano, vale cada centavo.',
        'O design é lindo e funciona perfeitamente. Estou muito satisfeita.',
        'Com certeza comprarei novamente, atendimento excelente.',
        'Chegou antes do prazo e bem embalado. Recomendo muito!',
        'Material muito resistente, parece que vai durar anos.',
        'O custo-benefício é imbatível. Pode comprar sem medo.',
        'Uso todos os dias e não tenho do que reclamar. Perfeito!',
        'A cor é ainda mais bonita pessoalmente. Amei!',
        'Fácil de instalar e configurar. Nota mil.',
        'Ganharam um cliente fiel. Qualidade impecável.',
        'Excelente! Exatamente como no anúncio.',
        'Surpreendente a rapidez da entrega. Produto top.',
        'Muito prático e eficiente. Facilitou muito minha vida.',
        'O atendimento da loja foi impecável, tiraram todas as dúvidas.',
        'Achei maravilhoso, super delicado e bem feito.',
        'Superou o que eu esperava. O acabamento é fino.',
        'Pode comprar de olhos fechados, a qualidade é premium.',
        'Leve, bonito e funcional. Nota 10/10.',
        'Gostei muito, o material é bem superior aos concorrentes.',
        'Veio tudo certinho e funcionando perfeitamente.',
        'Um dos melhores produtos que já usei nessa categoria.',
        'Fiquei impressionado com o capricho da embalagem.',
        'O suporte técnico foi muito atencioso quando precisei.',
        'Chegou muito rápido, em apenas 2 dias!',
        'Estou apaixonada por esse item, não tiro mais do corpo.',
        'Valeu muito o investimento. Recomendo de olhos fechados.',
        'Fácil de usar e o resultado é incrível.',
        'Exatamente o que eu estava procurando há meses.',
        'Muito satisfeito com a compra. Tudo 100%.',
        'Design moderno e alta performance. Sensacional.',
        'A qualidade do som e imagem é absurda de boa.',
        'O vendedor é super atencioso, nota máxima.',
        'Chegou em perfeito estado e é muito intuitivo.',
        'O preço é justo pela qualidade que entrega.',
        'Comprei para presente e a pessoa adorou!',
        'Não vivo mais sem esse produto. Essencial.',
        'Super prático para o dia a dia. Recomendo!',
        'Superou minhas expectativas em todos os sentidos.',
        'Bom demais! Recomendo a todos da comunidade.',
        'Achei incrível o cuidado com cada detalhe.',
        'Material de primeira linha. Muito robusto.',
        'Muito feliz com a aquisição, valeu cada real.',
        'O tamanho ficou perfeito, conforme a tabela de medidas.',
        'Muito bonito e elegante. Chama a atenção.',
        'Excelente aquisição, indico para todo mundo.',
        'A bateria dura muito mais do que o esperado.',
        'Simples, direto e funcional. Excelente produto.',
        'Parabéns pelo excelente trabalho e qualidade do item.',
        'Fiquei chocado com a qualidade, é nível profissional!',
        'O encaixe é perfeito e o conforto é sem igual.',
        'Chegou bem antes do combinado, nota dez para a logística.',
        'Um espetáculo de produto, recomendo para todos os amigos.',
        'O acabamento é impecável, nota-se o cuidado na fabricação.',
        'Funciona muito melhor do que marcas muito mais caras.',
        'A experiência de uso é fluida e sem bugs.',
        'Muito robusto, aguentou o uso pesado sem problemas.',
        'A melhor escolha que eu poderia ter feito.',
        'Vendedor honesto e produto original. Perfeito.',
        'O brilho e as cores são vibrantes, muito fiel às fotos.',
        'Extremamente leve, nem parece que estou carregando algo.',
        'A embalagem protegeu muito bem o produto no transporte.',
        'Cumpre 100% do que promete, estou impressionado.',
        'O manual é super explicativo, instalei em 5 minutos.',
        'A estética é moderna e combina com tudo.',
        'Ganhou meu coração, comprarei as outras cores com certeza.',
        'Não trava nunca, a velocidade de processamento é ótima.',
        'Pelo preço, eu não esperava algo tão luxuoso.',
        'Um achado! Preço baixo e qualidade altíssima.',
        'Muito macio e confortável, parece que estou nas nuvens.',
        'O suporte pós-venda resolveu meu problema em minutos.',
        'Indispensável para quem busca praticidade.',
        'Estou recomendando para toda a minha família.',
        'Nota máxima em todos os quesitos avaliados.',

        # --- NEGATIVOS (75) ---
        'Chegou quebrado e o suporte não me ajudou em nada. Decepcionante.',
        'Dinheiro jogado fora. O anúncio promete uma coisa e entrega outra.',
        'Muito caro para o que oferece. A bateria não dura nada.',
        'Pior experiência de compra da minha vida. Nunca mais!',
        'O manual é confuso e o material parece plástico barato.',
        'Não comprem! Estragou na primeira semana de uso.',
        'Estou tentando devolver há dias e ninguém responde.',
        'A cor é totalmente diferente da foto do site. Horrível.',
        'O produto veio faltando peças. Muita falta de respeito.',
        'Lento, trava o tempo todo e esquenta muito.',
        'Péssimo acabamento, cheio de rebarbas e defeitos.',
        'Não vale o preço que cobram. Muito frágil.',
        'A entrega atrasou duas semanas e o pacote veio amassado.',
        'Odiei. O cheiro é muito forte e desagradável.',
        'Muito pequeno, as fotos enganam o consumidor.',
        'Propaganda enganosa. Não recomendo para ninguém.',
        'Parou de funcionar do nada após um mês.',
        'O atendimento é péssimo, me trataram muito mal.',
        'Achei o material bem inferior ao que eu esperava.',
        'Não encaixa direito e fica soltando o tempo todo.',
        'Estou muito arrependido da compra. Dinheiro perdido.',
        'Veio com marcas de uso, parece que me enviaram um usado.',
        'Extremamente barulhento e difícil de limpar.',
        'Não cumpre nada do que está na descrição do produto.',
        'A qualidade caiu muito, o antigo era bem melhor.',
        'Frágil demais, quebrou só de encostar.',
        'Muito difícil de montar, as peças não batem.',
        'Tive que pagar para consertar logo após a garantia acabar.',
        'Ficou descascando em menos de 15 dias de uso.',
        'O tamanho é muito menor do que o padrão brasileiro.',
        'Me senti enganado pela publicidade desse produto.',
        'O suporte ao cliente é simplesmente inexistente.',
        'Não comprem, é pura perda de tempo e estresse.',
        'Veio com um risco enorme na frente. Falta de cuidado.',
        'O software é horrível e vive dando erro.',
        'Pedi azul e veio vermelho. Total desorganização.',
        'A caixa chegou toda aberta e o produto arranhado.',
        'Preço de ouro para qualidade de latão.',
        'Desisti de usar de tão complicado que é.',
        'Não recomendo, o material é muito ruim.',
        'Muito decepcionado com a durabilidade desse item.',
        'As funções não funcionam como deveriam. Falha total.',
        'Fui taxado e a loja não deu suporte algum.',
        'Cuidado! O produto é perigoso e quase me machucou.',
        'Demora uma eternidade para carregar.',
        'Simplesmente não funciona. Joguei no lixo.',
        'O acabamento é porco, parece que foi feito às pressas.',
        'Não dura nada ligado, decepção total.',
        'Material muito fino, rasgou no primeiro uso.',
        'Pior compra que já fiz na internet. Nota zero.',
        'A alça arrebentou no primeiro dia de uso. Lixo.',
        'Muito barulhento, impossível usar à noite.',
        'Sinto que fui roubado, o produto é uma porcaria.',
        'Não serve para nada, não comprem de jeito nenhum.',
        'O material é tão ruim que dá até vergonha de usar.',
        'Veio com defeito de fabricação e a troca é impossível.',
        'Esquenta tanto que tenho medo de explodir.',
        'É muito mais feio do que nas fotos do anúncio.',
        'Uma porcaria. Não percam o dinheiro de vocês.',
        'Trava até para abrir as funções básicas. Inútil.',
        'As peças são frouxas e o produto balança todo.',
        'O cheiro de química é insuportável, tive alergia.',
        'O suporte técnico me ignorou completamente.',
        'Veio sujo e com manchas de óleo. Um absurdo.',
        'O frete foi mais caro que o produto e não valeu a pena.',
        'Simplesmente parou de carregar do nada.',
        'A tela risca com qualquer coisa, péssima qualidade.',
        'O botão afundou e não volta mais. Frágil demais.',
        'Pensei que era original, mas é claramente uma réplica.',
        'Fui enganado pela marca, nunca mais compro nada deles.',
        'Não segura carga, tenho que deixar na tomada o tempo todo.',
        'Descascou na primeira lavagem. Produto descartável.',
        'O som é todo chiado e baixo. Não recomendo.',
        'Atraso absurdo e o SAC é um robô que não ajuda.',
        'Não comprem, é dor de cabeça garantida.'
    ],
    'sentimento': (
        ['positivo'] * 75 +
        ['negativo'] * 75
    )
}
df = pd.DataFrame(dados)

def pipeline_limpeza(texto):
  doc = nlp(texto.lower())
  tokens_limpos = []
  for token in doc:
    if not token.is_stop and not token.is_punct and not token.is_space:
      tokens_limpos.append(token.lemma_)
  return ' '.join(tokens_limpos)

df['comentario_limpo'] = df['comentario'].apply(pipeline_limpeza)
print('Textos após pré-processamento: ')
display(df[['comentario','comentario_limpo']])

from tkinter.constants import X
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split

vetorizador = CountVectorizer()
x = vetorizador.fit_transform(df['comentario_limpo'])
y = df['sentimento']

x_treino, x_teste, y_treino, y_teste = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)
modelo_nb = MultinomialNB()
modelo_nb.fit(x_treino, y_treino)
print('Modelo treinado com Sucesso...')

def analisador_sentimento(novo_texto):
  texto_limpo = pipeline_limpeza(novo_texto)
  vetor = vetorizador.transform([texto_limpo])
  previsao = modelo_nb.predict(vetor)[0]

  print(f'Comentário: {novo_texto}')
  print(f'Sentimento detectado: >>> {previsao.upper()} <<<')
  print('-' * 50)

analisador_sentimento('Nossa, eu simplesmente adorei a qualidade do material!')
analisador_sentimento('Produto chegou quebrado e o vendedor não responde. Péssimo!')
analisador_sentimento('Produto horrível! Odiei, não recomendo')
analisador_sentimento('Odiei o produto')
analisador_sentimento('AMEI o produto')
analisador_sentimento('Recomendo muito esse produto. Maravilhoso')
analisador_sentimento('Que produto maravilhoso, quebrou em 5 minutos de uso. Parabéns aos envolvidos.')