# -*- coding: utf-8 -*-
"""Aula9.1_IA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m8we5sc2v72p5c-7C-NLbdx_y0Hmu1FL
"""

# Contando palavras - PLN (Processamento de Linguagem Natural)

# Tokenização: computador separa uma string (texto) em palavras
# Computadores não formam conceitos a partir de frases, elas precisam ser fragmentadas e analizadas por separado.
#   Cada fragmento -> Token

from collections import Counter

texto = 'Eu gosto de estudar Machine Learning'
palavras = texto.split()
print(palavras)

contador = Counter(palavras)
print(contador)

texto2 = 'gatos cachorros gatos cachorros gatos passarinhos'
palavras2 = texto2.split()
contador = Counter(palavras2)
print(contador)

# Remover símbolos do texto usando a biblioteca re
import re
texto = 'Olá!!! Como você está? Tudo bem.'
texto_limpo = re.sub(r'[^\w\s]', '', texto)
print(texto_limpo)

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
textos = [
    'eu gosto de pizza',
    'eu gosto de sorvete',
    'pizza é deliciosa'
]
vetor = CountVectorizer()
X = vetor.fit_transform(textos)
print(vetor.get_feature_names_out())
print(X.toarray())

vetor = TfidfVectorizer() # Elimina o peso dos conectivos (de, o, a, etc.)
X = vetor.fit_transform(textos)
print(vetor.get_feature_names_out())
print(X.toarray())

from sklearn.naive_bayes import MultinomialNB

frases = [
    'gostei muito',
    'excelente produto',
    'péssimo produto',
    'odiei o produto'
    # Três frases coincidem na palavra 'produto'
]
rotulos = [
    'positivo',
    'positivo',
    'negativo',
    'negativo'
    # Duas frases com 'produto' são negativas e só uma é positiva. O rótulo para frases contendo 'produto' será 'negativo'.
]

vetor = CountVectorizer()
X = vetor.fit_transform(frases)

modelo = MultinomialNB()
modelo.fit(X, rotulos)

nova_frase = vetor.transform(['excelente produto']) # igual à frase de treinamento, portanto mesmo rótulo
print(modelo.predict(nova_frase)[0])

nova_frase = vetor.transform(['otimo produto']) # duas frases com 'produto' -> negativo, e uma frase com 'produto' -> positivo, portanto o rótulo de maior peso é o negativo
print(modelo.predict(nova_frase)[0])

from sklearn.pipeline import Pipeline

textos = [
    'time venceu campeonato',
    'o campeonato acabou',
    'governo anuncia medida',
    'novo celular lançado',
    'eleições começam amanhã',
    'vacina está em fase de testes',
    'a inflação diminuiu',
    'SENAI criou novos cursos gratuitos'
]
categorias = [ # Cada frase será rotulada com uma categoria
    'esporte',
    'esporte',
    'política',
    'tecnologia',
    'política',
    'saúde',
    'economia',
    'educação'
]
modelo = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('clf', MultinomialNB())
])

modelo.fit(textos, categorias)
print(modelo.predict(['novo campeonato de futebol'])[0])

# Sistema de ML para detectar mensagens spam
mensagens = [
    'você ganhou dinheiro',
    'promoção imperdível',
    'reunião às 15 horas',
    'bom dia equipe',
    'clique aqui para ganhar prêmio',
    'segue o relatório'
]
rotulos = [
    'spam',
    'spam',
    'normal',
    'normal',
    'spam',
    'normal',
]

modelo = Pipeline([
    ('vetor', CountVectorizer()),
    ('classificador', MultinomialNB())
])

modelo.fit(mensagens, rotulos)
mensagem_teste = modelo.predict(['ganhe prêmio agora'])
print(mensagem_teste[0])

mensagem_teste2 = modelo.predict(['reunião imperdível com pizza'])
print(mensagem_teste2[0])