# -*- coding: utf-8 -*-
"""Aula10.2_Detecção_rostos_CV2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TFG3TEvw1VNaXtZ4XedRkUDoXjY61dHq
"""

# Dependências que precisam ser instaladas
!pip install opencv-python
!pip install matplotlib
!pip install ultralytics
!pip install pandas
!pip install seaborn
!pip install face_recognition

# Importar dependências
import cv2
import matplotlib.pyplot as plt
import urllib.request

# Baixa uma imagem de exemplo
url = 'https://raw.githubusercontent.com/opencv/opencv/master/samples/data/lena.jpg'
urllib.request.urlretrieve(url, 'rosto.jpg')

# Lê a imagem
imagem = cv2.imread('rosto.jpg')

# Converte de BGR para RGB para exibir corretamente no matplotlib
imagem_rgb = cv2.cvtColor(imagem, cv2.COLOR_BGR2RGB)

# Mostra a imagem
plt.imshow(imagem_rgb)
plt.axis('off')
plt.show()

# Carrega o classificador Haar Cascade pré-treinado para detectar rostos
classificador = cv2.CascadeClassifier(
    cv2.data.haarcascades + 'haarcascade_frontalface_default.xml'
)

# Converte a imagem para escala de cinza
imagem_cinza = cv2.cvtColor(imagem, cv2.COLOR_BGR2GRAY) # imagem codificada em BGR

# Detecta rostos na imagem
faces = classificador.detectMultiScale(
    imagem_cinza,
    scaleFactor=1.1,
    minNeighbors=5
)

# Contorna os rostos encontrados com retângulos
for (x, y, w, h) in faces:
  cv2.rectangle(imagem_rgb, (x, y), (x + w, y + h), (255, 100, 0), 2)

# Mostra a imagem com a área do rosto contornada
plt.figure(figsize=(6,6))
plt.imshow(imagem_rgb)
plt.axis('off')
plt.show()

# Conta quantos rostos foram detectados
print('Rostos encontrados:', len(faces))

# Salva a imagem processada
cv2.imwrite('imagem_rosto_detectado.jpg', cv2.cvtColor(imagem_rgb, cv2.COLOR_RGB2BGR))