# -*- coding: utf-8 -*-
"""Aula10.3_Detecção_objetos_pessoas_YOLO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dvvJC7FH0T88ugxOPqRGvj9aVvDxWFiA
"""

# Instala os pacotes primeiro

!pip install opencv-python
!pip install matplotlib
!pip install ultralytics
!pip install pandas
!pip install seaborn
!pip install face_recognition

# ...e importa a bibilioteca de reconhecimento facial
import face_recognition
# Biblioteca para baixar URLs
import urllib.request

# Baixa duas imagens de exemplo
url1 = "https://raw.githubusercontent.com/ageitgey/face_recognition/master/examples/obama.jpg"
url2 = "https://raw.githubusercontent.com/ageitgey/face_recognition/master/examples/obama2.jpg"

urllib.request.urlretrieve(url1, 'foto1.jpg')
urllib.request.urlretrieve(url2, 'foto2.jpg')

# Carrega as imagens
imagem1 = face_recognition.load_image_file("foto1.jpg")
imagem2 = face_recognition.load_image_file("foto2.jpg")

# Extrai as características faciais das imagens
face1 = face_recognition.face_encodings(imagem1)[0]
face2 = face_recognition.face_encodings(imagem2)[0]

# Compara os rostos
resultado = face_recognition.compare_faces([face1], face2)

# Mostra se são a mesma pessoa
print('Os rostos pertencem à mesma pessoa?', resultado[0])

# Importa o YOLO
from ultralytics import YOLO

# Carrega o modelo pré-treinado YOLOv8, capaz de reconhecer pessoas e objetos
modelo = YOLO('yolov8n.pt')

# Baixa uma imagem de exemplo
url = "https://ultralytics.com/images/bus.jpg"
urllib.request.urlretrieve(url, "imagem.jpg")

# Detecta objetos na imagem
resultado = modelo("imagem.jpg")

# Mostra a imagem com os objetos detectados
resultado[0].show()