# -*- coding: utf-8 -*-
"""Aula6.1_IA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o0EAnsDl18Wbmij7jSZ03tI2p0iWFfcQ
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

dados_clientes = {
    'idade': [18, 20, 23, 26, 22,
              35, 39, 41, 40, 37,
              55, 56, 58, 61, 63],

    'gasto_mensal': [500, 650, 700, 850, 900,
                     2500, 2700, 2600, 3000, 3200,
                     6000, 6200, 6400, 6800, 7000]
}

df_clientes = pd.DataFrame(dados_clientes)
df_clientes

# Criando o modelo
modelo = KMeans(
    n_clusters=3,
    random_state=42
)
modelo.fit(df_clientes)

# Visualizando os dados
plt.figure(figsize=(7,5))
plt.scatter(df_clientes['idade'],
            df_clientes['gasto_mensal'])
plt.xlabel('Idade')
plt.ylabel('Gasto Mensal')
plt.title('Clientes')
plt.grid()
plt.show()

# Classificando/descobrindo os grupos
df_clientes['grupo'] = modelo.labels_
df_clientes

# Visualizando os clusters
plt.figure(figsize=(8,6))
plt.scatter(df_clientes['idade'],
            df_clientes['gasto_mensal'],
            c=df_clientes['grupo'],
            cmap='viridis',
            s=120)
plt.xlabel('Idade')
plt.ylabel('Gasto Mensal')
plt.title('Clusters encontrados pelo K-Means')
plt.grid()
plt.show()

# Visualizando os valores centrais (centróides) de cada cluster
centros = modelo.cluster_centers_
plt.figure(figsize=(8,6))
plt.scatter(df_clientes['idade'],
            df_clientes['gasto_mensal'],
            c=df_clientes['grupo'],
            cmap='viridis',
            s=120
)
plt.scatter(centros[:,0],
            centros[:,1],
            color='red',
            s=300,
            marker='X'
)
plt.xlabel('Idade')
plt.ylabel('Gasto Mensal')
plt.title('Clusters e Centróides')
plt.grid()
plt.show()

# Interpretando os grupos
df_clientes.groupby('grupo').mean()

# Como escolher a quantidade de grupos?
inercias = []
for k in range(1,11):
  modelo = KMeans(
      n_clusters=k,
      random_state=42
  )
  modelo.fit(df_clientes)
  inercias.append(modelo.inertia_) # soma as distâncias entre os quadrados de cada dado

plt.figure(figsize=(7,5))
plt.plot(range(1,11), inercias, marker='o')
plt.xlabel('Quantidade de Clusters')
plt.ylabel('Inércia')
plt.title('Método do cotovelo')
plt.grid()
plt.show()