# -*- coding: utf-8 -*-
"""Aula8.1_IA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CyKAYWFWU-P174jDoAEfX_cb4-KkxdHf
"""

# importando libs
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

# criando database
dados = pd.DataFrame({
    'idade':[18,22,25,28,30,
             32,35,38,40,42,
             45,48,50,52,55,
             58,60,62,65,68],

    'salario':[1800,2200,2500,2700,3000,
               3200,3500,3800,4200,4500,
               4800,5200,5500,6000,6500,
               7000,7500,8000,8500,9000],

    'compra': [0,0,0,0,0,
               0,1,1,1,1,
               1,1,1,1,1,
               1,1,1,1,1]
})

# separando entrada (X) e saída (y)
X = dados[['idade', 'salario']]
y = dados['compra']

# dividindo treino e teste
X_treino, X_teste, y_treino, y_teste = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# normalizando os dados
scaler = StandardScaler()
X_treino = scaler.fit_transform(X_treino)
X_teste = scaler.transform(X_teste)

# criando a rede neural
modelo = Sequential([
    Input(shape=(2,)),
    Dense(8, activation='relu'),
    Dense(4, activation='relu'),
    Dense(1, activation='sigmoid')
])

# compilando a rede
modelo.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# treinando a rede
historico = modelo.fit(
    X_treino,
    y_treino,
    epochs=100,
    verbose=1
)

# avaliando
loss, acc = modelo.evaluate(X_teste, y_teste)
print('Precisão: ', acc)

# fazendo previsões: features, idade e salário
novo_cliente = np.array([[36,4000]])
novo_cliente = scaler.transform(novo_cliente)
previsao = modelo.predict(novo_cliente)
print(previsao)