# -*- coding: utf-8 -*-
"""Aula10.1_IA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BWq-KjvwS8hn9DyzCjCItZ4CpMg6mS8l
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import Input

import matplotlib.pyplot as plt

# Criando database
np.random.seed(42)

clientes = pd.DataFrame({
    'tempo_empresa': np.random.randint(1,60,500), # inserir 500 valores entre 1 (inclusivo) e 60 (exclusivo)
    'idade': np.random.randint(18,70,500), # inserir 500 valores entre 18 (inclusivo) e 70 (exclusivo)
    'gastos': np.random.randint(50,1000,500),
    'reclamacoes': np.random.randint(0,10,500),
    'cancelou': np.random.randint(0,2,500)
})
clientes.head()

# Separando I/O
X = clientes.drop('cancelou', axis=1)
y = clientes['cancelou']

# Dividindo Treino e Teste
X_treino, X_teste, y_treino, y_teste = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Normalizando dados (a IA trabalha melhor com dados numéricos padronizados)
scaler = StandardScaler()
X_treino = scaler.fit_transform(X_treino)
X_teste = scaler.transform(X_teste)

# Construindo a rede neural
#modelo = Sequential([
#    Input(shape=(4,)),
#    Dense(16, activation='relu'),
#    Dense(8, activation='relu'),
#    Dense(1, activation='sigmoid')
#])

# ...utilizando o dobro de neurônios
modelo = Sequential([
    Input(shape=(4,)),
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compilando o modelo
modelo.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Treinando a rede neural
historico = modelo.fit(
    X_treino,
    y_treino,
    epochs=30,
    batch_size=16,
    validation_split=0.2
)

# Avaliando Modelo
loss, accuracy = modelo.evaluate(X_teste, y_teste)

print('Acurácia:', accuracy)

# Prevendo se um novo cliente irá cancelar ou não
novo_cliente = [[24,35,500,1]]
novo_cliente = scaler.transform(novo_cliente)
previsao = modelo.predict(novo_cliente)[0][0]
print(f'{(previsao * 100):.2f}')

# Gráfico de treinamento
plt.plot(historico.history['accuracy'])
plt.plot(historico.history['val_accuracy'])
plt.title('Acurácia')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend(['Treino','Validação'])
plt.show()